// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/lucasti79/meli-interview/internal/category"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) GetAll() ([]category.Category, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]category.Category, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []category.Category); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type RepositoryMock_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *RepositoryMock_Expecter) GetAll() *RepositoryMock_GetAll_Call {
	return &RepositoryMock_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *RepositoryMock_GetAll_Call) Run(run func()) *RepositoryMock_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryMock_GetAll_Call) Return(categorys []category.Category, err error) *RepositoryMock_GetAll_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *RepositoryMock_GetAll_Call) RunAndReturn(run func() ([]category.Category, error)) *RepositoryMock_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWithContext provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) GetAllWithContext(ctx context.Context) ([]category.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWithContext")
	}

	var r0 []category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]category.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []category.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_GetAllWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWithContext'
type RepositoryMock_GetAllWithContext_Call struct {
	*mock.Call
}

// GetAllWithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RepositoryMock_Expecter) GetAllWithContext(ctx interface{}) *RepositoryMock_GetAllWithContext_Call {
	return &RepositoryMock_GetAllWithContext_Call{Call: _e.mock.On("GetAllWithContext", ctx)}
}

func (_c *RepositoryMock_GetAllWithContext_Call) Run(run func(ctx context.Context)) *RepositoryMock_GetAllWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_GetAllWithContext_Call) Return(categorys []category.Category, err error) *RepositoryMock_GetAllWithContext_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *RepositoryMock_GetAllWithContext_Call) RunAndReturn(run func(ctx context.Context) ([]category.Category, error)) *RepositoryMock_GetAllWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) GetByName(name string) (*category.Category, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*category.Category, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *category.Category); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type RepositoryMock_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *RepositoryMock_Expecter) GetByName(name interface{}) *RepositoryMock_GetByName_Call {
	return &RepositoryMock_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *RepositoryMock_GetByName_Call) Run(run func(name string)) *RepositoryMock_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_GetByName_Call) Return(category1 *category.Category, err error) *RepositoryMock_GetByName_Call {
	_c.Call.Return(category1, err)
	return _c
}

func (_c *RepositoryMock_GetByName_Call) RunAndReturn(run func(name string) (*category.Category, error)) *RepositoryMock_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNameWithContext provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) GetByNameWithContext(ctx context.Context, name string) (*category.Category, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameWithContext")
	}

	var r0 *category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*category.Category, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *category.Category); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_GetByNameWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNameWithContext'
type RepositoryMock_GetByNameWithContext_Call struct {
	*mock.Call
}

// GetByNameWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *RepositoryMock_Expecter) GetByNameWithContext(ctx interface{}, name interface{}) *RepositoryMock_GetByNameWithContext_Call {
	return &RepositoryMock_GetByNameWithContext_Call{Call: _e.mock.On("GetByNameWithContext", ctx, name)}
}

func (_c *RepositoryMock_GetByNameWithContext_Call) Run(run func(ctx context.Context, name string)) *RepositoryMock_GetByNameWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryMock_GetByNameWithContext_Call) Return(category1 *category.Category, err error) *RepositoryMock_GetByNameWithContext_Call {
	_c.Call.Return(category1, err)
	return _c
}

func (_c *RepositoryMock_GetByNameWithContext_Call) RunAndReturn(run func(ctx context.Context, name string) (*category.Category, error)) *RepositoryMock_GetByNameWithContext_Call {
	_c.Call.Return(run)
	return _c
}
